-- An idempotency key for fills booked by hand.
--
-- `transactions_planned_action_id_idx` has protected queued confirmations since
-- August: a slow submit or a failed queue update cannot book the same intent
-- twice. Fills booked from the manual form carry no planned action, so they had
-- no key at all — and 2 of the 8 live buys took that route. The position sell
-- form has none either, and no sale has ever been booked.
--
-- The exposure is worse than a missing guard, because the failure invites the
-- mistake. `bookFill` and `bookSell` return `{ ok: false }` when a step *after*
-- the ledger insert fails, so the money has already moved and the screen says
-- the fill did not happen. Retrying is the natural response and the wrong one.
--
-- The form generates a UUID once per mount and sends it with the submit, so a
-- resubmit — a double-click, a refresh, a back-then-forward — carries the same
-- key and is recognised as the fill that already exists. A genuinely new fill is
-- a new form, and a new form is a new key.
--
-- Partial, like the planned-action index: a null stays unconstrained, so any
-- caller that does not send one still books exactly as it does today rather
-- than being refused. Protection is opt-in per submit; the absence of a key is
-- never an error.

alter table public.transactions
  add column client_key uuid;

create unique index transactions_client_key_idx
  on public.transactions (client_key)
  where client_key is not null;

comment on column public.transactions.client_key is
  'Idempotency key generated by the booking form, one per form mount. Makes a resubmitted manual fill or sale repair rather than double-book. Null for callers that do not send one.';
